### ISSUE TITLE
Where can i find alcali executeable?

### ISSUE THREAD

**Issue by SynPrime** [latenighttales/alcali#113]
Hello, your alcali-formula installed alcali on my salt-master. I can see the login-page already. Now, I would like to check the installation according https://alcali.dev/running/. I cant find the `alcali` executable. How can I get it?

**Comment by mattLLVW** [comment]
Hi, 
If you used the alcali-formula it should have created a dedicated user (by default `alcali`) and a virtualenv (by default in `/opt/alcali/.venv`).
So, you should be able to activate the virtualenv as the `alcali` user:
```bash 
source /opt/alcali/.venv/bin/activate
```
And the `alcali` command will be in your path.

**Comment by SynPrime** [comment]
Thanks for your reply,
I tried your advise, but I cant find the executable. The `alcali` command should be in bin directory of `.venv`, but there are only the python packages like `gunicorn` or `pepper`.
The formula-states passed the highstate.

I modified the formula, so I don't want the dedicated `alcali` user. The deploy dir is in a subdir of my salt user. But I think this shouldn't be the problem. Do you have another advice?

**Comment by mattLLVW** [comment]
alright, so the formula should have clone the repository in `{{ alcali.deploy.directory }}/code`.

**With the virtualenv activated** you can simply do:
`python <path you set >/code/manage.py`
instead of `alcali` command.

**Comment by SynPrime** [comment]
Thank you very much!
Great work, I like the webapp.
