### ISSUE TITLE
Can't access minion details

### ISSUE THREAD

**Issue by edouardch** [latenighttales/alcali#138]
On the screen "Minions" I get a 404 error when wan't to access Minion details

1. Go to Minions list
2. Click on a minion name
4. See error : nothing in the middle of the screen

In the Firefox network console we see the url : http://localhost:8001/api/minions/minion_name/
I don't see anything to answer the request in the class : MinionsViewSet

**Expected behavior**
https://github.com/latenighttales/alcali#minion-details

**Desktop :**
 - OS: linux
 - Browser firefox 
 - Version 71.0
- Git Branch : 2019.2

**Comment by kvedder-amplex** [comment]
I think I have had this issue as well. I can't see minions details.

**Comment by mattLLVW** [comment]
Hi and thanks for the issue.

Few questions:

- Are your keys present in the [keys view](https://alcali.dev/views/keys/) ?

- Are you able to refresh your minions in the [minions view](https://alcali.dev/views/minions/) ?

The 404 error would mean that the minion you're trying to see is not present in the database. Refreshing minions should fix it.

We should display some message though.

**Comment by edouardch** [comment]
- Yes I see all keys (45) in the key view ?
- I can refresh minions in the minion view.

**Comment by mattLLVW** [comment]
So you have 45 minions on the minion view, right?
Have you tried deleting the minion and refreshing them?
Is it not working for all minions?

**Comment by edouardch** [comment]
Yes I see all 45 minions in the minion view.
I deleted them all several times.

On the MinionDetail.vue method loadData() call "api/minions/" + this.minion_id + "/" can you explain shortly where put a breakpoint to debug this request on python side.

**Comment by mattLLVW** [comment]
the view called is [this](https://github.com/latenighttales/alcali/blob/1dd279cb27ee376134137b5069857f04130a4fd5/api/views/alcali.py#L99) one. It's a ModelViewSet as described in the DRF [documentation](https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset).
If you want to fidle with the retrieve method, you could override it like in this [example](https://www.django-rest-framework.org/api-guide/viewsets/#example).
But to get the object, we use the minion_id field, not the pk.
I think i have an idea of what's going on.
Could you provide an example of a minion id you are using?
As a minion_id, we only accept characters matching this regex: `[0-9a-zA-Z.]+`

**Comment by edouardch** [comment]
All my minion_id have dashes, with the new regex everything is ok
