### ISSUE TITLE
[Question] Dockerfile Entrypoint/Command

### ISSUE THREAD

**Issue by jbkc85** [latenighttales/alcali#160]
hey there,

we started trying to set of alcali via Salt recently using a typical systemd file and ran into issues due to some of the Dockerfile configurations.  I was wondering the following:

1. Why are you using an entrypoint.sh just accepting the `command` portion of Docker?

2. Why not define a default command in the generic Dockerfile (ie: `python manage.py runserver 0.0.0.0:8000`) as it seems thats the only command this container should support?

Anyway, great project!  I am happy we get to start using it!

**Comment by mattLLVW** [comment]
Hey @jbkc85 thanks for trying Alcali!

1. It seems like the right thing to do, the image provide everything one need to use Alcali.

2. If you look at the [docker-compose](https://github.com/latenighttales/alcali/blob/develop/docker-compose-ci.yml) file we use for the CI, we're using gunicorn to serve the project.
There's also the [custom command](https://alcali.dev/running/) to help troubleshoot and manage the project (granted it's just a wrapper of manage.py ...).

Thanks for the kind words!

**Comment by jbkc85** [comment]
gotcha!  Well, if you dont mind the suggestion... Though I am not 100% on how to get rid of the entrypoint (as realistically you can swap that out w/ docker-compose too), why not add a default COMMAND argument to the Dockerfile?  This way for anyone starting up, they would only change the command upon altering the default behavior of the docker container - which would be starting up the app.

Anyway, sorry it took me so long to get back to this...the email notification got lost :-(

**Comment by rosscdh** [comment]
You can override the docker entrypoint commend at runtime as well .. `docker run image_name:tag $command @args` which in salt/systemd es simple enough to do; or just pass in the gunicorn/uwsgi/whatever_u_use_in_prod_to_run_django command

**Comment by jbkc85** [comment]
> You can override the docker entrypoint commend at runtime as well .. `docker run image_name:tag $command @args` which in salt/systemd es simple enough to do; or just pass in the gunicorn/uwsgi/whatever_u_use_in_prod_to_run_django command

Yup.  Overriding is super easy - its just a matter of making sure the 'default state' of the container is always the foremost priority of running the container.

Either way its no biggy, just wanted to throw it out there as an observation.

**Comment by rosscdh** [comment]
Yep I tend to agree.. the container should indeed "startup" and run only the primary service (alcali) as per the spec; you are also right in that its not really well documented.

Id also suggest not using runserver/runserver_lpus as they are specifically not meant for production use; rather gunicorn or uwsgi .. maybe a PR is in order
