### ISSUE TITLE
Password Changes Not Stored Correctly

### ISSUE THREAD

**Issue by agreenbhm** [latenighttales/alcali#163]
**Describe the bug**
When updating passwords in the Alcali User's section, password changes are incorrectly stored in the database, preventing users from logging in.

**To Reproduce**
1. Go to 'Users'.
2. Click on 'Update' for a user.
3. Set a new password for the user, then click 'Update'.
4. Log out and attempt to log back in with the changed password.
5. User will not be able to log in using original or new passwords.

**Expected behavior**
Expected: password properly changed.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 78

**Server:**
 - Build: Latest

**Additional context**
If you look at the "auth_user" table in the database, you can see that newly created users passwords begin with "pbkdf2_sha256$180000$", while the updated passwords display in cleartext.  It seems as if the PBKDF2 function is not being executed on the password string when received by the server.

**Comment by mattLLVW** [comment]
Good catch!
i blame DRF: too much magic, or not enough! :sweat:

**Comment by mattLLVW** [comment]
@agreenbhm it should be ok now.
I'll release a new version soon!

**Comment by agreenbhm** [comment]
@mattLLVW I just pulled the latest changes and can confirm it is working.  Thanks for the prompt fix!
