### ISSUE TITLE
Upgrade to whitenoise 5.0.1 is throwing error #155

### ISSUE THREAD

**Issue by anitakrueger** [latenighttales/alcali#166]
**Describe the bug**
After upgrading to 2019.3.4 which includes https://github.com/latenighttales/alcali/pull/155 whitenoise gets updated to 5.0.1.
When that happens, I see the following error in the alcali logs which eventually produce a 501 and the UI never comes up:

```
Feb 14 10:18:34 ip-10-3-2-225 alcali: /usr/local/lib/python3.6/site-packages/whitenoise/base.py:116: UserWarning: No directory at: /usr/local/lib/python3.6/site-packages/dist/static/
Feb 14 10:18:34 ip-10-3-2-225 alcali: warnings.warn(u"No directory at: {}".format(root))
```

**To Reproduce**
1. Upgrade to 2019.3.4 and watch whitenoise being updated to 5.0.1
2. Restart alcali
3. Just try to hit the main page

**Expected behavior**
UI should come up.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 79.0.3945.130

**Additional context**
I've installed alcali from pypi, so I'm not sure if I maybe missing another package to fix this.
I found https://github.com/uktrade/data-hub-api/pull/1157 but this was fixed a long time ago.

**Comment by mattLLVW** [comment]
this was a tough one.
 `dist/__init__.py` was removed so when packaging the wheel, MANIFEST.in dist directory was ignored.

If you upgrade it should be fine now.
