### ISSUE TITLE
Layout broken on 1080p in Firefox (Ubuntu)

### ISSUE THREAD

**Issue by gizahNL** [latenighttales/alcali#170]
**Describe the bug**
The layout seems broken, with some elements appearing outside of their boxes, or some boxes being set to sizes that require scrolling

**To Reproduce**
Set resolution to 1080p open the application in Firefox (I'm on version 73)

**Expected behavior**
Elements fitting within their borders, elements that don't require additional scroll

**Screenshots**
![2020-02-19_09-09](https://user-images.githubusercontent.com/8005186/74814675-1a9bb300-52f8-11ea-89bb-0fea5b680472.png)
![2020-02-19_09-11](https://user-images.githubusercontent.com/8005186/74814672-1a031c80-52f8-11ea-8a23-b163635c5a81.png)
![2020-02-19_09-10](https://user-images.githubusercontent.com/8005186/74814834-68182000-52f8-11ea-9a52-9ad5cc027421.png)

**Desktop (please complete the following information):**
 - Ubuntu Eoan
 - Firefox 73

**Comment by gizahNL** [comment]
3 screenshots as example, however problem appears on more pages

**Comment by bbrendon** [comment]
Yea, I noticed that on Chrome / Windows as well.

**Comment by mattLLVW** [comment]
It's a known problem, i had a hard time figuring out how to structure the Vuetify project to have a consistent layout.
I'm quiet sure it's an easy fix.

**Comment by mattLLVW** [comment]
@gizahNL @bbrendon It's fixed in develop branch and will be included in a futur release.
