### ISSUE TITLE
Issue with LDAP authentication

### ISSUE THREAD

**Issue by geofflhenderson** [latenighttales/alcali#172]
I have configured Alcali with ldap authentication and confirmed that I can login to the UI using my ldap credentials.

I have also configured the ldap external_auth configuration on the Salt side, and it also appears to be working, for example I can do the following:

salt -a ldap minion test.ping
username: ghenderson
password: XXXXXX

minion:
    True

However, if I try to run the test.ping command against a minion from within Alcali, I get an "authentication denied" error.  The following log message is observed in the Salt Master log:

2020-02-20 20:34:29,833 [salt.master      :2108][WARNING ][28231] Authentication failure of type "token" occurred.

Here  is my Salt configuration:

**salt-api.conf**

external_auth:
  rest:
    ^url: http://alcali:8000/api/token/verify/
    admin:
      - .*
      - '@runner'
      - '@wheel'

rest_cherrypy:
  port: 8080
  host: 0.0.0.0
  debug: False
  disable_ssl: True
  expire_responses: False
  rest_timeout: 3600

**ldap-auth.conf**

auth.ldap.server: myldapserver
auth.ldap.port: 389
auth.ldap.scope: 2
auth.ldap.tls: False
auth.ldap.activedirectory: True
auth.ldap.persontype: person
auth.ldap.basedn: mybasedn
auth.ldap.binddn: mybinddn
auth.ldap.bindpw: XXXXXXX
auth.ldap.filter: sAMAccountName={{ username }}
auth.ldap.accountattributename: sAMAccountName

external_auth:
  ldap:
    ghenderson:
      - '*':
        - .*
        - '@runner'
        - '@wheel'

**Comment by mattLLVW** [comment]
The good news is that it's not an issue with the LDAP auth.
It looks like your salt-master can't validate your user.
According to your config, you have an `admin` user in your rest external auth, but you're using  `ghenderson` to login on alcali. both users must have the same username.

**Comment by geofflhenderson** [comment]
OK, I got this working now, thank you for the explanation.
