### ISSUE TITLE
Unable to delete minions

### ISSUE THREAD

**Issue by geofflhenderson** [latenighttales/alcali#173]
I have a few minions that no longer exist - their salt-keys were deleted after installing Alcali but directly from the Salt Master and not through the Alcali webui.  These minions no longer show in the "Keys" view of Alcali, however they still show up in the "Minions" view.

I get the following error when trying to delete the minion using the "Delete" button in the "Minions" view:

{ "detail" : "not found: }

They also do not disappear if I refresh the minions.

These minions also have schedules configured against them for highstate conformity checks.  I get an "authentication" denied error if I try to delete these schedules.  I am able to delete schedules for valid minions however.

**Comment by mattLLVW** [comment]
I am unable to reproduce this issue, how did you install Alcali? (from git, pypi, docker) and what version are you using?

Are you able to see the details of minions? (in previous versions there was a bug if your minion is named with a character like "_-" it could be the issue you're facing.

**Comment by geofflhenderson** [comment]
I installed using the Salt formula.  I work with the person that opened the latest bug for minions containing dashes, at which pointed we upgraded to the latest 2019.2 version.  So, at the moment, we are running:

# alcali version
3.0.3

I can reproduce by doing the following:

1. Install a salt minion and pull it into Alcali so it shows under the Keys and Minions section
2. On the Salt Master, delete the minion key:  salt-key -d <minion>
3. In Alcali, refresh the keys.  The minion id longer shows in the Keys section.
4. In Alcali, refresh the minions list.  The minion id that was just delete still shows in the Minions section.  
5. Click the Delete button and the "detail:notfound" error occurs

**Comment by VietTPham** [comment]
I want to chime in on this as well. running Alcali 2019.2.4 in docker.
And I am getting same problem.
Deleted minion keys on Aalcali and refresh, deleted minion key does not show up anymore
On Minion page, if I delete the minion on this page I get the same error "{ "detail" : "not found: }"

I analyze what happen when you click delete on the minion page and it does this call
> curl 'https://<ip>/api/minions/<minion id>' -X DELETE <bearer and cookie here>

**Comment by mattLLVW** [comment]
@geofflhenderson i still can't reproduce this.

To get the Alcali version you should run:

```bash
alcali current_version
```

It really fit the previous bug. Could you give an example of the `minion_id` you're trying to delete?

Have you tried other minions?

**Comment by geofflhenderson** [comment]
@mattLLVW alcali current_version is showing: alcali version 2019.2.4.post0

An example minion id is usla-junk-d001.dev.voobiquiti,com

**Comment by mattLLVW** [comment]
I'm trying to figure out what's going on.

Could you please:

Open the javascript console and check what url is called when deleting the minion?

It should look like this:

![delete_minion](https://user-images.githubusercontent.com/15060182/76678461-84963800-65d8-11ea-861a-842f9ede6146.png)

**Does the last fragment of the url exactly match the name of the minion you are trying to delete?**

ex: foo.bar:8000/api/minions/**usla-junk-d001.dev.voobiquiti,com**/

**Comment by geofflhenderson** [comment]
@mattLLVW yes, it appears to exactly match the name of the minion I am trying to delete.

xhr.js:178 DELETE http://usla-alci-p001.vubiquity.com:8000/api/minions/usla-dckr-d001.dev.voobiquiti.com 

404 (Not Found)
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:52
Promise.then (async)
l.request @ Axios.js:61
n.forEach.l.<computed> @ Axios.js:76
(anonymous) @ bind.js:9
deleteMinion @ MinionsTable.vue:224
click @ MinionsTable.vue?21ff:13
it @ vue.runtime.esm.js:1854
i @ vue.runtime.esm.js:2179
it @ vue.runtime.esm.js:1854
Li.e.$emit @ vue.runtime.esm.js:3888
click @ VBtn.js:125
it @ vue.runtime.esm.js:1854
i @ vue.runtime.esm.js:2179
Zr.s._wrapper @ vue.runtime.esm.js:6917

**Comment by mattLLVW** [comment]
@geofflhenderson ok, do you have a direct access to Alcali database?

Could you do something like:

```bash
mysql -u<DB_USER> -p salt
SELECT count(*) FROM salt_minions WHERE minion_id = 'usla-dckr-d001.dev.voobiquiti.com';
``` 
or the equivalent in Postgres.

It will probably be count = 1.

Also doing a refresh of the page and flushing the cache doesn't help, right? `Ctrl+Maj+R`

**Comment by geofflhenderson** [comment]
@mattLLVW  the query provided does in fact result in count = 1.  I've tried refreshing the page and using the "refresh all minions" functionality in the UI, but the minion still shows.

**Comment by mattLLVW** [comment]
@geofflhenderson did you update to the last version of Alcali?
Is the problem still present?

**Comment by VietTPham** [comment]
I can confirmed that it is working for me, using the latest docker image.

**Comment by geofflhenderson** [comment]
@mattLLVW - apologies for the delay.  I just upgraded and it appears to have fixed the problem.  Thank you.
