### ISSUE TITLE
Ability for users to change their own passwords

### ISSUE THREAD

**Issue by iostat** [latenighttales/alcali#181]
**Describe the feat you'd like**
All users should have the ability to change their own passwords. It seems that right now only `Staff Users` can change everyone's passwords, including their own, but regular users have no means to set or reset their own passwords.

**Is your feature request related to a problem? Please describe.**
At this point, the only way for a user's password to be changed is to have a `Staff User` do it. Allowing users to self-serve password changes will make the system more secure as the staff users who would change a user's password would ideally have no possible of means of knowing the password a user selected.

**Comment by mattLLVW** [comment]
@iostat Yes, user management is lacking. If you think about other obvious enhancement like that, don't hesitate to create an issue. Thanks!

**Comment by iostat** [comment]
Happy to help! This is by far the nicest Salt dashboard I've come across so far, so thanks for all your hard work!

**Comment by mattLLVW** [comment]
It's fixed on develop branch and will be included in next release.
Normal users are now able to see only themselves in Users view, and update all of their settings except `is_staff` status . They are not able to create or delete users.

**Comment by mattLLVW** [comment]
Available on 2019.2.5 and 3000.1.0
