### ISSUE TITLE
Updating any user info through the Users view forces a password change

### ISSUE THREAD

**Issue by iostat** [latenighttales/alcali#182]
**Describe the bug**
If you update a user (e.g., change their name or email), you also have to enter a password for the user prior to clicking update. If left blank, the user will be unable to log in with their existing password nor with an empty password

**To Reproduce**
1. Create a user with username `hello` and password `world`, first name, last name, email irrelevant
2. Log in as `hello`/`world` to verify account was created correctly
3. Log back into a staff user, and change any of the user's info but leave password blank as it is when the screen opens.
4. Attempt to log in as `hello`/`world` again and fail with `invalid username/password`
5. Attempt to log in as `hello` and leave the password blank to receive the same `invalid username/password` error
6. Log back in as a Staff User and update `hello`'s password with anything, and try logging in as `hello` with the password you just set, you should succeed.

**Expected behavior**
After step 3, `hello`'s password should have remained unchanged, and step 4 should have succeeded.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Browser: Firefox 74.0, Safari 13.0.5, Chrome 80.0.3987.132
 - Version: 2019.2.4 from Dockerhub

**Additional context**
Running Saltstack 3000, but given the user database is managed by Alcali I don't believe this should be a contributing factor.

**Comment by mattLLVW** [comment]
Related to #163 .
Now we use the correct method to store passwords in db, but javascript isn't happy when we send an empty string...

'password': 'undefined'

**Comment by mattLLVW** [comment]
It's fixed on develop branch by #184  and will be included in next release.

**Comment by mattLLVW** [comment]
Available on 2019.2.5 and 3000.1.0
