### ISSUE TITLE
no connection to ws and empty results from minion and key list

### ISSUE THREAD

**Issue by ctr49** [latenighttales/alcali#234]
**Describe the bug**
No information is displayed in Alcali. Websocket is reported as "NOT OK", keys and minion refresh result in empty response.
Using the browser console I can see the call to /api/event_stream is failing (empty response, aborted after 30s)

**To Reproduce**
1. Install alcali (3000.1.0) from pip in virtualenv, using Python 3.8
2. (Re)configure salt-master, salt-api and alcali according to documentation
3. using "rest" authentication method 
4. go to http://localhost:5000
5. see error "Salt WebSocket | NOT OK"

**Expected behavior**
Alcali can connect to salt and displays information.

**Screenshots**
installed python modules:
```
Package                       Version
----------------------------- ---------
alcali                        3000.1.0
ansi2html                     1.5.2
asgiref                       3.2.10
certifi                       2020.6.20
chardet                       3.0.4
Django                        3.0.5
django-cors-headers           3.2.1
django-currentuser            0.5.0
djangorestframework           3.11.0
djangorestframework-simplejwt 4.4.0
gunicorn                      20.0.4
idna                          2.10
mysqlclient                   2.0.1
pip                           20.1.1
PyJWT                         1.7.1
python-dotenv                 0.12.0
pytz                          2020.1
requests                      2.23.0
salt-pepper                   0.7.5
setuptools                    49.1.0
six                           1.15.0
sqlparse                      0.3.1
urllib3                       1.25.9
wheel                         0.34.2
whitenoise                    5.0.1
```

alcali check output:
```
$ alcali check
db:	ok
env:	ok
```

.env:
```
DB_BACKEND=mysql
DB_NAME=<redacted>
DB_USER=<redacted>
DB_PASS=<redacted>
DB_HOST=localhost
DB_PORT=3306

SECRET_KEY=<redacted>
ALLOWED_HOSTS=*
MASTER_MINION_ID=<redacted>

SALT_URL=http://127.0.0.1:8080
SALT_AUTH=rest

DJANGO_DEBUG=true
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Version: 83

**Additional context**
eauth works in general, I can successfully login to salt-api using the alcali-supplied token and then also connect to /events, /minions and /keys (seeing valid output) in salt-api with the resulting token. So the problem is not salt-api / cherrypy or (e)auth related.

In Alcali log I can see:
```
[2020-07-05 17:14:24 +0200] [18691] [CRITICAL] WORKER TIMEOUT (pid:22934)
[2020-07-05 10:14:24 -0500] [22934] [INFO] Worker exiting (pid: 22934)
[2020-07-05 17:14:24 +0200] [24310] [INFO] Booting worker with pid: 24310
```

and once in a while:
`Unauthorized: /api/event_stream/`
(in those cases there is also 401 visible in the browser console instead of the timeout/empty response)

**Comment by mattLLVW** [comment]
Could you put your salt master in debug mode and check the logs.
It's probably a connectivity issue.
Here is a sample configuration for rest auth:
```yaml
external_auth:
  rest:
    ^url: http://web:8000/api/token/verify/
    apiuser:
      - test.ping
    admin:
      - .*
      - '@runner'
      - '@wheel'


```
Using this configuration as an example, if a user name "apiuser" is logged into alcali, the websocket should be ok, and sending test.ping command should work as expected.

It should be more clear in the docs that using the rest auth, the master must be able to communicate with alcali.

**Comment by mattLLVW** [comment]
@ctr49 did you manage to fix your issue?

**Comment by tobiasvdk** [comment]
I'm trying to debug the login to alcali, running on Debian buster. The login via the web ui works correctly. The login via `curl` times out:
```
$ curl -isSk https://localhost:5000/api/token/verify -d username="alcali" -d password="alcali"
curl: (28) Operation timed out after 300165 milliseconds with 0 out of 0 bytes received
```

Is this the correct way using `curl` to test the login?

**Comment by mattLLVW** [comment]
If the login via the web ui works correctly, then you can find out by opening your console and looking at the network tab, but yes it looks like it's the correct way of using curl to test the login.

**Comment by ctr49** [comment]
Sorry I didn't have time to work with alcali for some time but just gave it another try with 3003.1.0 (latest release available via pip). I still have exactly the same problem as described above.
When starting salt-master with debugging enabled I can see the call to /api/token/verify/ (which also retruns with a 200). So it is not a connctivity issue between alcali and salt-master (which are running on the same host for my tests btw).

@mattLLVW would you mind to reopen this one or shall I open a new issue?
