### ISSUE TITLE
Timeouts trying to refresh minions list

### ISSUE THREAD

**Issue by bcstechdept** [latenighttales/alcali#235]
**Describe the bug**
I am experiencing timeouts when trying to refresh my Minions list in Alcali.  I am able to import all my minion keys and schedules correctly and without issue.  When refreshing the Minions list, Alcali refreshes two CentOS 7 and 8 minions correctly but stalls out once it gets to my Windows minions.  The minion refresh job always seems to time out after sending the request to about 3-5 minions.  

My setup is a little complicated.  Alcali and my salt master are two separate VMs.  My master is using a MySQL cluster for event returns which Alcali is also pointed at.  I am using the REST endpoint for authentication.  

**To Reproduce**
1. Install Alcali
2. Setup Salt infrastructure with ~120 minions with a mixture of CentOS 7/8, Windows 7/2008/2012/2016, and FreeBSD 12
3. Configure salt-master appropriately to interact with Alcali, reload salt-master and salt-api
4. Import minion keys in to Alcali
5. Attempt to refresh minions list in Alcali

**Expected behavior**
Alcali to update minion information

**Screenshots**
```
[alcali@alcali alcali]$ alcali version
3.0.5
[alcali@alcali alcali]$ alcali check
db:	ok
env:	ok
[alcali@alcali alcali]$ cat .env
DB_BACKEND=mysql
DB_NAME=salt
DB_USER=saltstack
DB_PASS=[sanitized]
DB_HOST=mysql.domain.tld
DB_PORT=3306

SECRET_KEY=
ALLOWED_HOSTS=*
MASTER_MINION_ID=salt.domain.tld

SALT_AUTH=rest
SALT_URL=http://salt.domain.tld:8080
```
  

Versions report from my master:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.12
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.13.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
On the master, I have the following set to help speed things up pre-Alcali:
```
minion_data_cache: True
cache: localfs
```
![overall-status](https://user-images.githubusercontent.com/11198386/88698761-557df000-d0bb-11ea-9b4a-5bfcf92c4776.png)
![minions-list](https://user-images.githubusercontent.com/11198386/88698770-57e04a00-d0bb-11ea-9fbc-1e8da4401f48.png)
  
After several of the refresh jobs start returning, an nginx timeout error will display at the bottom of the screen.
![nginx-timeout](https://user-images.githubusercontent.com/11198386/88699833-b22dda80-d0bc-11ea-8248-005919f4470d.png)
  
and the following appears in /var/log/nginx/error.log:
```
2020/07/28 10:20:55 [error] 28067#0: *1206 upstream prematurely closed connection while reading upstream, client: 172.16.19.15, server: _, request: "GET /api/event_stream/ HTTP/1.1", upstream: "http://127.0.0.1:8000/api/event_stream/", host: "alcali.domain.tld", referrer: "http://alcali.domain.tld/"
2020/07/28 10:21:26 [error] 28067#0: *1208 upstream prematurely closed connection while reading upstream, client: 172.16.19.15, server: _, request: "GET /api/event_stream/ HTTP/1.1", upstream: "http://127.0.0.1:8000/api/event_stream/", host: "alcali.domain.tld", referrer: "http://alcali.domain.tld/"
2020/07/28 10:21:44 [error] 28067#0: *1201 upstream prematurely closed connection while reading response header from upstream, client: 172.16.19.15, server: _, request: "POST /api/minions/refresh_minions/ HTTP/1.1", upstream: "http://127.0.0.1:8000/api/minions/refresh_minions/", host: "alcali.domain.tld", referrer: "http://alcali.domain.tld/"
2020/07/28 10:21:57 [error] 28067#0: *1220 upstream prematurely closed connection while reading upstream, client: 172.16.19.15, server: _, request: "GET /api/event_stream/ HTTP/1.1", upstream: "http://127.0.0.1:8000/api/event_stream/", host: "alcali.domain.tld", referrer: "http://alcali.domain.tld/"
```

![jobs](https://user-images.githubusercontent.com/11198386/88700049-fcaf5700-d0bc-11ea-8019-989fca4e21a1.png)

**Desktop (please complete the following information):**
 - OS: Fedora 32 - Cinnamon 4.6.6
 - Browsers: Chrome 84.0.4147.89 & Firefox 78.0.2

**Additional context**
Things I've tried:
Downgraded msgpack from 0.6.2 to 0.5.6 as per Salt bugs [57026](https://github.com/saltstack/salt/issues/57026), [53230](https://github.com/saltstack/salt/issues/53230), [54884](https://github.com/saltstack/salt/issues/54884), [55180](https://github.com/saltstack/salt/issues/55180), [55184](https://github.com/saltstack/salt/issues/55184)
  
Modified the following in master config:
```
gather_job_timeout: 7200
timeout: 7200
event_return_queue: 20
max_event_size: 3048576
state_events: True
runner_returns: True
```
  
Modified under rest_cherrypy on the master:
```
expire_responses: False
rest_timeout: 7200
socket_queue_size: 60
```
  
On the VM running Alcali, I am using Nginx as a reverse proxy.  I've also tried adjusting the ```client_max_body_size``` variable up to 300M in case it was nginx terminating the data stream early.

**Comment by bcstechdept** [comment]
I also used to have all my minions running a highstate sync every 2 hours, regardless of OS or if they actually had a state to apply on the master or not.  Apparently, this is an issue on Windows [48964](https://github.com/saltstack/salt/issues/48964) and [51621](https://github.com/saltstack/salt/issues/51621) so we had to drop Windows from the schedule.

**Comment by mattLLVW** [comment]
Hey,
I'm guessing you're using Gunicorn to serve Alcali to Nginx. Try increasing the timeout setting: https://docs.gunicorn.org/en/stable/settings.html#timeout

**Comment by bcstechdept** [comment]
Hi @mattLLVW 
  Thank you for the Gunicorn timeout suggestion; that appears to have done the trick.  I am still dialing in the correct setting for my environment but I now have 80+ minion details instead of 5.

**Comment by Timbus** [comment]
I ran into the same issue as this, and it looks like there are other reports similar here, regarding windows hosts just taking nearly forever to load.
SaltGUI seems to have no issues loading hosts so I'm wondering if there's a difference in the way you're gathering data that could be improved. Maybe listing them could be caching the keys and minion IDs, fetching additional data could be done in the background? Just a passing thought, as I like this UI but currently cannot use it.

**Comment by mattLLVW** [comment]
@Timbus the thing is, how Alcali works there shouldn't be any problem.
Acali takes its infos in the database, so as long as your DB and Salt are properly configured, it should be ok. If the minion return the job correctly, and Salt store it in its DB, Alcali should be able to display it.
i.e if you run the issues @bcstechdept are listing are Salt related issue, and there's not much i can do.
If you have a specific Alcali problem, please open another issue.

**Comment by arsa-dev** [comment]
@Timbus as I see at https://github.com/latenighttales/alcali/blob/develop/api/views/alcali.py#L107 if you pass minion_id parameter to POST api/minions/refresh_minions/ you can add/refresh only pending minions, error management is still a todo (at https://github.com/latenighttales/alcali/blob/develop/api/backend/netapi.py#L75), so take in mind that minion should be able to reply grains.items at the moment of request.
Due to wip error management there is no way to know with response if minion is refreshed/added or not, but you can refresh list of minions at GUI and search it.
This can be really useful to make alcali working on environments with lot of minions, but requires a bit of code from your own to call this api.
