### ISSUE TITLE
Minions not listed in ui, but exists

### ISSUE THREAD

**Issue by vskubriev** [latenighttales/alcali#272]
**Describe the bug**
Fresh install of alcali(3000.1.0) from pip. Fresh install of salt (3001.1)

One clarification.
Firefox reports an `Uncaught (in promise) TypeError: Error in body stream`

**Expected behavior**
WebUI should list minions, but `api/minions` endpoint returns empty response. Despite `http://salt/api/userssettings/1/` returns valid response. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4639077/100090920-f8c1f480-2e64-11eb-9987-7604a07e2ea2.png)
![image](https://user-images.githubusercontent.com/4639077/100091119-3de62680-2e65-11eb-8ed8-ad2da8b1f5b5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [firefox, chrome]
 - Version [latest stable]

That's may be misconfiguration.

**Comment by vskubriev** [comment]
Keys page returns minion keys installed on master properly. Refresh minions is also called successfully.

![image](https://user-images.githubusercontent.com/4639077/100093066-0e84e900-2e68-11eb-9614-c7208f972c55.png)

**Comment by vskubriev** [comment]
Done some debug by added code like follows (used pickle):

```
class MinionsViewSet(viewsets.ModelViewSet):
    queryset = Minions.objects.all()

    with open('queryset.pkl', 'wb') as output:
        pickle.dump(queryset, output, pickle.HIGHEST_PROTOCOL)

    serializer_class = MinionsSerializer
    lookup_field = "minion_id"
    lookup_value_regex = "[^/]+"

    @action(detail=False, methods=["post"])
    def refresh_minions(self, request):
```

queryset in 

```
class KeysViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Keys.objects.all()
    serializer_class = KeysSerializer
```

exists. so in web there is minions keys

queryset in `MinionsViewSet` is empty. There are no minions in queryset dumped in `MinionsViewSet`

**Comment by mattLLVW** [comment]
Have you used the action button and refresh all minions on the minions view?

https://alcali.dev/views/minions/

Can you please check what the network tab says?

**Comment by vskubriev** [comment]
> Have you used the action button and refresh all minions on the minions view?
> 
> https://alcali.dev/views/minions/
> 
> Can you please check what the network tab says?

Sure. I did it many times. Suppose there are misconfiguration in setup. But network tab in browser doesn't have and issues now.

Console tab sometimes shows very strange `Uncaught (in promise) TypeError: Error in body stream` error. But sometimes.

Here's what I noticed additionally at minions page. After a while, errors appear on the console tab on the minions page like below:

![image](https://user-images.githubusercontent.com/4639077/100713472-64581480-33c5-11eb-9d97-3d268512e2f4.png)

I did a little research on this issue, but unfortunately cannot understand where is my issue appears. What is its reason

**Comment by rosscdh** [comment]
I had the same issue there is an error in the codebase.. I patched it myself will try find the fix I used this in my branch at

https://github.com/rosscdh/alcali/blob/feature/django-extensions/api/models.py#L160

will make a PR if this is interesting for anyone else (the branch above implements dango-extensions which is very useful set of helpers for auto loading models and whatnot in shell_plus also enabled runserver_plus which uses Werkzeug which is good fro debugging in dev

**Comment by vskubriev** [comment]
@rosscdh perfect. Thank you for a reply. It would be great to see a PR. 

To be honest we chose a pip version. There is no time to redo the assembly of containers and selected flow now.

It's enough [patch](https://github.com/rosscdh/alcali/commit/f5d9d649e349546db6fe8905cd5b32e2466393a6) ? 

Or Jun 13 Commits is also contain some necessary fixes of this bug?

**Comment by rosscdh** [comment]
Try https://github.com/latenighttales/alcali/pull/281

**Comment by vskubriev** [comment]
Excellent! Will wait for a maintainer.

**Comment by mattLLVW** [comment]
new version published.

**Comment by rosscdh** [comment]
You're welcome :) keep up the good work..

just noticed things get hairy with salt-syndics

**Comment by ThEWiZ76** [comment]
Sorry to bump this, but just updated the docker container to latest, confirmed running Alcali version 3003.1.0, Salt master 3003 but no minions appear. I see the jobs, I have a green OK in Salt Websocket, but after refresh still no minions. 
<img width="576" alt="n48e0mvluevrj9" src="https://user-images.githubusercontent.com/4500465/115932956-4aab8c80-a48e-11eb-8d30-8ff02a1de616.png">

**Comment by mattLLVW** [comment]
Hey @ThEWiZ76 first, thanks for the sponsoring :)
I just tried with the new docker image and _it works on my laptop_
What's in your screenshot seems related only to the salt websocket.

Do you have accepted minions in your keys? Otherwise Alcali won't refresh Minions.(https://alcali.dev/views/minions/)
If you still have trouble, let me know.

**Comment by ThEWiZ76** [comment]
o/ I'm the guy that mailed today ;)
But websocket is running fine, I have 22 active minions running on the master, with active keys. Websocket is running fine:
<img width="334" alt="b91d6g44zdthtl" src="https://user-images.githubusercontent.com/4500465/115934448-5187ce80-a491-11eb-9fa9-3bd23a42a429.png">
Jobs are showing up without an issue:
![b3597c4b8023be0bd478c42aa95696f6](https://user-images.githubusercontent.com/4500465/115934540-86942100-a491-11eb-84d5-78f0bde15749.png)

**Comment by mattLLVW** [comment]
Yeah but no keys in Alcali DB!
See: https://github.com/latenighttales/alcali/blob/a78052d1bb28f7a5eac467921252a92e345c90c1/api/views/alcali.py#L115-L119
maybe that's not how we should check which minions are available...
Just refresh keys in the keys view, then refresh minions, and you should be fine

**Comment by ThEWiZ76** [comment]
Thanks, after reviewing the code and tracing the steps I see the keys, but now I have a new issue 🙈 
Refreshing the minions after seeing the keys available in the corresponding tab, still does not show the minions. I get a "minions refreshed" but no minions. After inspecting the api logging I see this. Does this give any hints?
`2021-04-24 00:57:37,345 [salt.client      :1095][WARNING ][19158] jid does not exist`

**Comment by mattLLVW** [comment]
@ThEWiZ76 looking at the warning you're having it looks like a salt issue, more specifically:
https://github.com/saltstack/salt/blob/2a5fd5e3e3defbb90375bafabb9f19eed180a51a/salt/client/__init__.py#L1095
it's used in event_return.
how is it configured?
see configuration example: https://alcali.dev/installation/#database-access-and-master-job-store-configuration
