### ISSUE TITLE
No module name 'bin'

### ISSUE THREAD

**Issue by pjanzen** [latenighttales/alcali#277]
I have a fresh install of alcali and when I run commands like alcali check it fails.

```
(.venv) alcali@saltweb1-prd-nl1-oss:~$ alcali check
Traceback (most recent call last):
  File "/home/alcali/.local/bin/alcali", line 7, in <module>
    from bin import manage
ModuleNotFoundError: No module named 'bin'
(.venv) alcali@saltweb1-prd-nl1-oss:~$ alcali current_version
Traceback (most recent call last):
  File "/home/alcali/.local/bin/alcali", line 7, in <module>
    from bin import manage
ModuleNotFoundError: No module named 'bin'
```

I am unsure if this is reproducible on other systems. I create a fresh virtual env and ran pip install --user alcali and pip install -- user alcali[ldap]

I am running this on 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

(.venv) alcali@saltweb1-prd-nl1-oss:~$ python -V
Python 3.6.9

**Comment by mattLLVW** [comment]
I think it's because you installed from pip. I will release a new version soon.

**Comment by mattLLVW** [comment]
new version published.
