### ISSUE TITLE
[Question] how are minions.

### ISSUE THREAD

**Issue by pjanzen** [latenighttales/alcali#279]
Hi,

I have successfully manages to setup Alcali and are able to login with the ldap backend. However, when I click on minions for example I do not see any data. How is this data is collected? Is this scheduled?

Regards,
Paul.

**Comment by rosscdh** [comment]
its hooked up to a mysql database; so you need to also configure salt to use the mysql backend so that runs and other data are stored there (in the docs i believe)

**Comment by rosscdh** [comment]
you will also need to setup the database schema you find at https://alcali.dev/installation/
