### ISSUE TITLE
superuser cannot login

### ISSUE THREAD

**Issue by VietTPham** [latenighttales/alcali#282]
**Describe the bug**
I had my server working with alcali a few week back, and decided to rebuild it from my own saltstack config.
This was install using source.
ran alcali migrate then alcali createsuperuser to create my user, but I cannot login with new user.

Tested that the salt-api with https works using pam auth.
Tested that alcali has access to salt database.

alcali check pass both db and env
**To Reproduce**
my /etc/salt/master config

```conf_file: /etc/salt/master
pki_dir: /etc/salt/pki/master
autosign_grains_dir: /etc/salt/autosign_grains
file_roots:
  base:
    - /srv/salt
hash_type: sha512
pillar_roots:
  base:
    - /srv/pillar
rest_cherrypy:
  port: 8080
  host: 0.0.0.0
  debug: True
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
external_auth:
  pam:
    my_username:
    - .*
  rest:
    ^url: http://127.0.0.1:8000/api/token/verify/
    my_username:
      - .*
      - '@runner'
      - '@wheel'
event_return: mysql
master_job_cache: mysql
mysql.host: 'localhost'
mysql.user: 'salt'
mysql.pass: 'salt'
mysql.db: 'salt'
mysql.port: 3306
```

/opt/alcali/.env
```DB_BACKEND=mysql
DB_NAME=salt
DB_USER=alcali
DB_PASS=alcali
DB_HOST=127.0.0.1
DB_PORT=3306
SECRET_KEY=changeme
ALLOWED_HOSTS=*
MASTER_MINION_ID={{grains['id']}}
SALT_URL=https://127.0.0.1:8080
SALT_AUTH=rest
```

**Expected behavior**
User should be able to login

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 84

**Additional context**
I am on ubuntu 18.04 with salt 3002.2

**Comment by VietTPham** [comment]
I tested the alcali docker image and it works, so I know my salt-api and mysql are working properly.

**Comment by mattLLVW** [comment]
probably related to #294
It's fix on develop and i'll release a new version this weekend.
