### ISSUE TITLE
Minion listing should not be coupled with Alcali key db

### ISSUE THREAD

**Issue by mattLLVW** [latenighttales/alcali#326]
We should just do something like `test.ping` to list minions connected
See: https://github.com/latenighttales/alcali/blob/a78052d1bb28f7a5eac467921252a92e345c90c1/api/views/alcali.py#L115-L119

**Comment by ggiesen** [comment]
I haven't delved into the code, but is there any reason to not use the manage.status runner?

**Comment by mattLLVW** [comment]
@ggiesen manage.status is publishing test.ping **and** needs `@runner` permissions.
