### ISSUE TITLE
Cannot log into alcali GUI

### ISSUE THREAD

**Issue by darmadoo** [latenighttales/alcali#352]
I was following the guide from https://alcali.dev/installation using the formula method authenticating using REST. 
The salt master server and the alcali server is on different boxes. 
Salt master -> 10.0.0.1
Alcali -> 10.0.0.2 

I was able to get the alcali service up. 
<img width="821" alt="Screen Shot 2021-06-07 at 11 07 58 PM" src="https://user-images.githubusercontent.com/3698288/121116870-34ab1e80-c7e5-11eb-878a-fdeca885c5c1.png">

I also created the superuser using `./manage.py createsuperuser`, and verified that i see the user in the DB on the alcali server (salt.auth_user) 

I did the checks as provided in the guide. 
<img width="425" alt="Screen Shot 2021-06-07 at 11 09 23 PM" src="https://user-images.githubusercontent.com/3698288/121116984-67edad80-c7e5-11eb-87b8-0ab3d010486b.png">

However, when I try to login at http://10.0.0.2:5000/#/login. I get an error like this: 
<img width="1440" alt="Screen Shot 2021-06-07 at 11 12 17 PM" src="https://user-images.githubusercontent.com/3698288/121117403-142f9400-c7e6-11eb-8a83-c75b5795a6cf.png">

I am positive that the salt-api works because I am able to create a token for the user using `./manage.py manage_token devops` and use that token to login
`
curl --noproxy '*' -si http://10.0.0.1:8000/login \
-c ~/cookies.txt \
-H "Accept: application/json" \
-H "Content-type: application/json" \
-d '{
    "username": "devops",
    "password": "<token from .manage.py>",
    "eauth": "rest"
}'
`
and then grab all the minions
`
curl --noproxy '*' -b ~/cookies.txt -si http://10.0.0.1:8000/ \
    -H "Accept: application/json" \
    -d client='local' -d tgt='*' -d fun='test.ping'
`

Any help would be appreciated! Thank you!

**Comment by mattLLVW** [comment]
Your version of Alcali seems a bit old (latest is 3003.1.0) but that's strange. you're getting a 500 error.

Did you do the migration?

**Comment by darmadoo** [comment]
Should I upgrade to the develop branch? 3000.1 seems to be the latest non develop branch on Github. 

I also did the migration.

**Comment by darmadoo** [comment]
So I checked out the new develop branch, did a `pip install -r requirements/prod.txt ` and restarted the service and I am able to log into the dashboard! I am testing out all the functionality to see if everything works and I will update you
