### ISSUE TITLE
[Question] pgjsonb vs postgres_alcali returners

### ISSUE THREAD

**Issue by sticky-note** [latenighttales/alcali#355]
I am wondering what the advantage to use `postgres_alcali.py` returner over standard `postgres` ou `pgjsonb` returners and which one  would be better to use.

**Comment by keslerm** [comment]
I think it's probably the same story as the mysql one that was covered here https://github.com/latenighttales/alcali/issues/263

**Comment by mattLLVW** [comment]
exactly :)
