### ISSUE TITLE
Minions not shown in the web UI (docker-environment): event_stream 401 (Unauthorized)

### ISSUE THREAD

**Issue by drscream** [latenighttales/alcali#363]
**Describe the bug**

Minions are not shown in the web UI but keys are accepted and shown. By loading the UI (and tab) the following console output is shown:

```
eventsource.js:533 GET http://127.0.0.1:8000/api/event_stream/ 401 (Unauthorized)
...
eventsource.js:796 EventSource's response has a status 401 Unauthorized that is not 200. Aborting the connection.
```

**To Reproduce**

I use the official docker environment provided in the `develop` branch.

1. `git clone https://github.com/latenighttales/alcali.git`
2. `cd alcali`
3. `docker-compose up --scale minion=2`

**Expected behavior**

Minions should be displayed at the Minions tab in the web UI. Especially by using the provided docker environment.

**Comment by mattLLVW** [comment]
you have to refresh minions as per the [docs](https://alcali.dev/walkthrough/#add-minions). this message is (kind of) normal.
