### ISSUE TITLE
Unable to execute a commande before parsing modules from a minion

### ISSUE THREAD

**Issue by baby-gnu** [latenighttales/alcali#387]
**Describe the bug**

On a fresh installation of Alcali, I can't run a `test.ping` because alcali try to run `null`.

**To Reproduce**
1. Having a salt-master with one or more minion
2. Install a fresh alcali
3. Go to `Run` menu
4. Click in `Target` field
5. Input `*` to target all minions
6. Click in `Function` field
7. Input `test.ping`
8. Click on `Run` button

**Expected behavior**

The `Results` should dispaly the list of minion with `True` as output.

<details><summary>Output of a successful job</summary>

![alcali-run-ok](https://user-images.githubusercontent.com/1233212/135061898-b6d4a0c8-51a3-4ea6-810c-ac54ef752ab2.png)
</details>

**Screenshots**

<details><summary>Output of running the failed job</summary>

![alcali-run](https://user-images.githubusercontent.com/1233212/135060398-9793e0e1-557b-4606-b878-bc92bab976c5.png)
</details>

<details><summary>Details of the failed job</summary>

![alcali-null-job](https://user-images.githubusercontent.com/1233212/135060723-9439234f-bda7-4244-b698-e62afd503b45.png)
</details>

**Desktop (please complete the following information):**
 - OS: Debian Sid
 - Browser Firefox
 - Version 88.0.1-1

**Additional context**

**Comment by buffman23** [comment]
@baby-gnu I found the problem. You have to make the combo-box lose focus before hitting run. That way the selectedFunction variable in javascript gets updated. 

Here is a stackoverflow post of someone with a similar issue: https://stackoverflow.com/questions/63896901/problem-with-updating-model-in-vuetify-combobox

**Comment by mattLLVW** [comment]
fixed by #450
