### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by gizahNL** [latenighttales/alcali#506]
**Describe the bug**
Is Alcali abandoned? I don't see any activity for over a year, while plenty of PR's are still open.

**Comment by mattLLVW** [comment]
just updated :smile:

**Comment by gizahNL** [comment]
Awesome! Those performance changes suggested by ITJamie look very interesting, do they look viable to you?

And thank you for updating! :)

**Comment by mattLLVW** [comment]
i'll implement #440 right away but #502 has too many changes that need discussing

**Comment by gizahNL** [comment]
Looks like there is a bug in the alcali.py auth file ;) (complains about missing six, importing six fixed it for me)

**Comment by mattLLVW** [comment]
#508 fixed it :)

**Comment by morsik** [comment]
Last commit 2 years ago... so question remains again: is this abandoned, or just nothing important changed? ;)
