### ISSUE TITLE
Salt Web Socket: NOT OK

### ISSUE THREAD

**Issue by soap1337** [latenighttales/alcali#55]
Greetings!
first of all this project is amazing and the best looking admin/monitoring tool I have seen so far for salt!

question: so I have alcali fully running but I am seeing an error on the dash board where the salt web socket status is 'not ok.' When I watch debugs and look at logs I do see http 401s on a numberof API requests,  but I cannot for the life of me find where the authentication is not happening or incorrect, where would you recommend I start investigating this?  thanks in advance!

**Comment by mattLLVW** [comment]
Hey,

Thanks for the kind words!

The authentication part in the docs are definitely not clear enough.

There's also the troubleshooting part missing, we'll update the docs very soon.

In the mean time, here's few steps that might help you:

First, make sure that the salt-api is working correctly: you can try [this](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#authentication) `curl` command using pam authentication and see if you can login

If the salt-api works with pam auth, then there's probably an issue with the [alcali authentication](https://alcali.dev/installation/#authentication):
- Is the auth module accessible to salt? (it should be in a sub folder called `auth` of the [file_roots](https://docs.saltstack.com/en/latest/ref/file_server/file_roots.html#directory-overlay)
- Have you run `salt-run saltutil.sync_all` on the salt-master? it is needed for the salt-master to "see" the auth module.

Log messages of the salt-api and salt-master should tell you if the module is found and auth is successful.
there's also a salt-master configuration in the [repository](https://github.com/latenighttales/alcali/blob/2019.2/docker/saltconfig/etc/master) as an example.

Let us know if it helps.

**Comment by soap1337** [comment]
thanks for the response! update on my end:
it appears to be something with my local RHEL server and how my company is securing the OS.  I had all the directories in place as a file structure on the Native OS vs containerizing each piece. when I run it fully containerized (master+minion+alcali-web+db) it all works flawlessly when running  for the first time. 

this will be how I run it from now on, the only pice I think ill play with is not containerizing the minions.

resolved, reason being: "my local environment caused this initial problem"

thanks alcali team!
